package edu.uwp.cs.android.sco.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table COURSE.
 */
public class Course {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String category;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Course() {
    }

    public Course(Long id) {
        this.id = id;
    }

    public Course(Long id, String name, String category) {
        this.id = id;
        this.name = name;
        this.category = category;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getCategory() {
        return category;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory(String category) {
        this.category = category;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
