package edu.uwp.cs.android.sco.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table RELATION_COURSE_STUDENT.
 */
public class RelationCourseStudent {

    private Long id;
    private long studentId;
    private long courseId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public RelationCourseStudent() {
    }

    public RelationCourseStudent(Long id) {
        this.id = id;
    }

    public RelationCourseStudent(Long id, long studentId, long courseId) {
        this.id = id;
        this.studentId = studentId;
        this.courseId = courseId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getStudentId() {
        return studentId;
    }

    public void setStudentId(long studentId) {
        this.studentId = studentId;
    }

    public long getCourseId() {
        return courseId;
    }

    public void setCourseId(long courseId) {
        this.courseId = courseId;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "RELATION --> StudentID: " + studentId + ", CourseID: " + courseId;
    }
    
    // KEEP METHODS END

}
