package edu.uwp.cs.android.sco.entities;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.Query;
import de.greenrobot.dao.QueryBuilder;

import edu.uwp.cs.android.sco.entities.RelationCourseStudent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table RELATION_COURSE_STUDENT.
*/
public class RelationCourseStudentDao extends AbstractDao<RelationCourseStudent, Long> {

    public static final String TABLENAME = "RELATION_COURSE_STUDENT";

    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StudentId = new Property(1, long.class, "studentId", false, "STUDENT_ID");
        public final static Property CourseId = new Property(2, long.class, "courseId", false, "COURSE_ID");
    };

    private Query<RelationCourseStudent> course_StudentsQuery;
    private Query<RelationCourseStudent> student_CoursesQuery;

    public RelationCourseStudentDao(DaoConfig config) {
        super(config);
    }
    
    public RelationCourseStudentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String sql = "CREATE TABLE " + (ifNotExists? "IF NOT EXISTS ": "") + "'RELATION_COURSE_STUDENT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'STUDENT_ID' INTEGER NOT NULL ," + // 1: studentId
                "'COURSE_ID' INTEGER NOT NULL );"; // 2: courseId
        db.execSQL(sql);
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'RELATION_COURSE_STUDENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RelationCourseStudent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getStudentId());
        stmt.bindLong(3, entity.getCourseId());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RelationCourseStudent readEntity(Cursor cursor, int offset) {
        RelationCourseStudent entity = new RelationCourseStudent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // studentId
            cursor.getLong(offset + 2) // courseId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RelationCourseStudent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStudentId(cursor.getLong(offset + 1));
        entity.setCourseId(cursor.getLong(offset + 2));
     }
    
    @Override
    protected Long updateKeyAfterInsert(RelationCourseStudent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RelationCourseStudent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "students" to-many relationship of Course. */
    public synchronized List<RelationCourseStudent> _queryCourse_Students(long studentId) {
        if (course_StudentsQuery == null) {
            QueryBuilder<RelationCourseStudent> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.StudentId.eq(studentId));
            course_StudentsQuery = queryBuilder.build();
        } else {
            course_StudentsQuery.setParameter(0, studentId);
        }
        return course_StudentsQuery.list();
    }

    /** Internal query to resolve the "courses" to-many relationship of Student. */
    public synchronized List<RelationCourseStudent> _queryStudent_Courses(long courseId) {
        if (student_CoursesQuery == null) {
            QueryBuilder<RelationCourseStudent> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.CourseId.eq(courseId));
            student_CoursesQuery = queryBuilder.build();
        } else {
            student_CoursesQuery.setParameter(0, courseId);
        }
        return student_CoursesQuery.list();
    }

}
